name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Download and Extract Gradle Wrapper JAR
      run: |
        wget https://services.gradle.org/distributions/gradle-8.2-bin.zip -O gradle-8.2-bin.zip
        unzip gradle-8.2-bin.zip gradle-8.2/lib/gradle-wrapper-8.2.jar -d .
        mv gradle-8.2/lib/gradle-wrapper-8.2.jar gradle/wrapper/gradle-wrapper.jar
        rm -rf gradle-8.2-bin.zip gradle-8.2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
